version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - DATABASE_URL=postgres://postgres:753869@db:5432/eduzz
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 753869
      POSTGRES_DB: eduzz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
